FROM postgres:15

WORKDIR /app

RUN apt-mark hold postgresql-15 postgresql-client-15 postgresql-common postgresql-client-common
RUN apt-get update -qq && apt-get install postgresql-plpython3-15 -qq -y
RUN apt-get -y install python3-pip -qq
RUN  apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

COPY requirements.txt requirements.txt

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
