FROM python:3.9

WORKDIR /app

COPY requirements.txt requirements.txt
COPY ingest.py ingest.py
COPY ./data/Reviews.csv ./data/Reviews.csv

RUN pip install -r requirements.txt
RUN apt update && apt install vim
# ENTRYPOINT ["python", "ingest.py"]

ENTRYPOINT ["bash"]